### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by handicraftsman** [xpl/wyg#1]
Is it necessary to use nodejs to implement this editor into classic (apache2-like) site?

**Comment by xpl** [comment]
NodeJS is used only for purposes of serving the demo page in this project (and building, but there's no build script for now).

Actually, in it's current state, it is not meant to be used by anyone, it's just a research project of mine. It will need to undergo hard refactoring before it could actually be used. If only I could find a time for that...

**Comment by handicraftsman** [comment]
I am writing CSS+JS library. If you want' i'll make module for this editor in JS part.
